var class_undertale_mod_lib_1_1_models_1_1_undertale_sequence_1_1_text_keyframes =
[
    [ "Data", "class_undertale_mod_lib_1_1_models_1_1_undertale_sequence_1_1_text_keyframes_1_1_data.html", "class_undertale_mod_lib_1_1_models_1_1_undertale_sequence_1_1_text_keyframes_1_1_data" ]
];